# SEC EDGAR Fetcher Configuration

# Required: Your contact information for SEC (they require this)
user_agent: "akalekar@purdue.edu"

# How often to check for new filings (in seconds)
# Note: While set to 0.2 seconds, actual request timing will be rate-limited
# to comply with SEC's limits (10 requests/second)
check_interval_seconds: 0.2

# NOTE: The system monitors all recent filings from the SEC EDGAR RSS feeds,
# not just specific companies. The feeds are checked for new 10-K, 10-Q, 8-K,
# and 6-K filings across all publicly traded companies.
#
# The specific company list below is maintained for reference but not used by the
# main fetcher. It is only used by fetch_test.py for targeted testing.

# List of companies for testing purposes only
companies:
  - name: "Apple Inc."
    cik: "0000320193"
  - name: "Microsoft Corporation"
    cik: "0000789019"
  - name: "Alphabet Inc."
    cik: "0001652044"
  # Add more companies as needed 